### ISSUE TITLE
两个小问题想请教一下

### ISSUE THREAD

**Issue by qhacking** [wangziyingwen/AutoApiS#12]
成功的部署上了，但目前有几个不太确定的信息想确认一下，谢谢

第一个是原教程中注册应用是使用 e5 管理员账号。但我注意到 e5 管理员账号不是 office 365 开发者账号，（这真的让我很蛋疼，微软在搞啥逻辑），同时 e5 管理员似乎不能给 office 365 开发者账号分配许可（因为不是 @域.onmicrosoft.com 邮箱）。然后我有看到一些网上的教程说是要使用开发者账号来触发api， 目前我是用 e5 管理员账号触发的，请问究竟是使用哪一个呢？

第二个问题是（虽然我知道这个 api 方法不是一定保证续订成功，但我们假设目前还可以续订成功的话），请问是调用 api 活跃度达到一定程度（也就是这个项目部署好一段时间后）会自动进行续订的吗？是否需要在微软账号上做任何操作（比如绑定信用卡？）如果是自动续订是会等到 90 天许可到期时自动续订还是说（比如一个礼拜内）活跃度达到标准了就会马上续订呢？

非常感谢！

**Comment by Mading706** [comment]
1.因为api调用是基于Microsoft Graph Code，所以帐号应该是E5管理员帐号。（至于这是什么逻辑，恐怕只有微软自己知道了。。）

2.这还是微软的神仙逻辑。。。通常在到期前一个月内发送邮件，但具体是哪一天目前还找不到规律。据说要求不是很高，所以大概率还是可以活的。至于绑定信用卡，没有特殊需求其实不是很必要。

**Comment by qhacking** [comment]
@Mading706 好的好的，非常感谢！
